grocery_app/main/routes.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from datetime import date, datetime
from flask_login import login_required, current_user
from grocery_app.models import GroceryStore, GroceryItem, User
from grocery_app.main.forms import GroceryStoreForm, GroceryItemForm

# Import app and db from events_app package so that we can run app
from grocery_app.extensions import app, db

main = Blueprint("main", __name__)

##########################################
#           Routes                       #
##########################################

@main.route('/')
def homepage():
    all_stores = GroceryStore.query.all()
    print(current_user)
    return render_template('home.html', all_stores=all_stores)

@main.route('/new_store', methods=['GET', 'POST'])
@login_required
def new_store():
    # TODO: Create a GroceryStoreForm
    form = GroceryStoreForm()
    # TODO: If form was submitted and was valid:
    # - create a new GroceryStore object and save it to the database,
    # - flash a success message, and
    # - redirect the user to the store detail page.
    if form.validate_on_submit():
        new_store = GroceryStore(
            title=form.title.data,
            address=form.address.data,
            created_by_id=current_user.id
        )
        db.session.add(new_store)
        db.session.commit()

        flash('New store was created successfully.')
        return redirect(url_for('main.store_detail', store_id=new_store.id))
    # TODO: Send the form to the template and use it to render the form fields
    return render_template('new_store.html', form=form)

@main.route('/new_item', methods=['GET', 'POST'])
@login_required
def new_item():
    # TODO: Create a GroceryItemForm
    form = GroceryItemForm()
    # TODO: If form was submitted and was valid:
    # - create a new GroceryItem object and save it to the database,
    # - flash a success message, and
    # - redirect the user to the item detail page.
    if form.validate_on_submit():
        new_item = GroceryItem(
            name=form.name.data,
            price=form.price.data,
            category=form.category.data,
            photo_url=form.photo_url.data,
            store=form.store.data,
            created_by_id=current_user.id
        )
        db.session.add(new_item)
        db.session.commit()

        flash('New item was created successfully.')
        return redirect(url_for('main.item_detail', item_id=new_item.id))
    # TODO: Send the form to the template and use it to render the form fields
    return render_template('new_item.html', form=form)

@main.route('/store/<store_id>', methods=['GET', 'POST'])
@login_required
def store_detail(store_id):
    store = GroceryStore.query.get(store_id)
    # TODO: Create a GroceryStoreForm and pass in `obj=store`
    form = GroceryStoreForm(obj=store)
    # TODO: If form was submitted and was valid:
    # - update the GroceryStore object and save it to the database,
    # - flash a success message, and
    # - redirect the user to the store detail page.
    if form.validate_on_submit():
        store.title = form.title.data
        store.address = form.address.data
        db.session.commit()

        flash('Store was updated successfully.')
        return redirect(url_for('main.store_detail', store_id=store.id))
    # TODO: Send the form to the template and use it to render the form fields
    return render_template('store_detail.html', store=store, form=form)

@main.route('/item/<item_id>', methods=['GET', 'POST'])
@login_required
def item_detail(item_id):
    item = GroceryItem.query.get(item_id)
    # TODO: Create a GroceryItemForm and pass in `obj=item`
    form = GroceryItemForm(obj=item)
    # TODO: If form was submitted and was valid:
    # - update the GroceryItem object and save it to the database,
    # - flash a success message, and
    # - redirect the user to the item detail page.
    if form.validate_on_submit():
        item.name = form.name.data
        item.price = form.price.data
        item.category = form.category.data
        item.photo_url = form.photo_url.data
        item.store = form.store.data
        db.session.commit()

        flash('Item was updated successfully.')
        return redirect(url_for('main.item_detail', item_id=item.id))
    # TODO: Send the form to the template and use it to render the form fields
    return render_template('item_detail.html', item=item, form=form)

@main.route('/add_to_shopping_list/<item_id>', methods=['POST'])
@login_required
def add_to_shopping_list(item_id):
    """Add item to user list"""
    item = GroceryItem.query.get(item_id)
    if item in current_user.shopping_list_items:
        flash("Item already in shopping list.")
        return redirect(url_for('main.item_detail', item_id=item.id))
    current_user.shopping_list_items.append(item)
    db.session.commit()
    flash("Item added to shopping list successfully.")
    return redirect(url_for('main.item_detail', item_id=item.id))

@main.route('/delete_from_shopping_list/<item_id>', methods=['POST'])
@login_required
def delete_from_shopping_list(item_id):
    """Remove item from user list"""
    item = GroceryItem.query.get(item_id)
    if item in current_user.shopping_list_items:
        current_user.shopping_list_items.remove(item)
        db.session.commit()
        flash("Item removed from shopping list successfully.")
    return redirect(url_for('main.shopping_list'))

@main.route('/shopping_list')
@login_required
def shopping_list():
    user_shopping_list = current_user.shopping_list_items
    return render_template('shopping_list.html', shopping_list=user_shopping_list)

# @main.route('/reset_db')
# def reset_db():
#     db.drop_all()
#     db.create_all()
#     flash('Database has been reset.')
#     return redirect(url_for('main.homepage'))

grocery_app/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Grocery Store Tracker</title>
        <link rel="stylesheet" href="/static/style.css">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap" rel="stylesheet">
    </head>
    <body>
        <div id="content">
            {% for message in get_flashed_messages() %}
                <p>{{ message }}</p>
            {% endfor %}
            <nav>
                <a href="/">Home</a>
                <div>
                    {% if current_user.is_authenticated %}
                        <a href="/new_store">New Store</a>
                        <a href="/new_item">New Item</a>
                        <a href="/shopping_list">Shopping List</a>
                        <a href="/logout">Log Out</a>
                    {% else %}
                       <a href="/signup">Sign Up</a>
                       <a href="/login">Log In</a> 
                    {% endif %}
                </div>
            </nav>
            {% block content %}{% endblock %}
        </div>
    </body>
</html>

grocery_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Grocery Store Tracker</h1>

<p><em>The best place to track prices and find the hottest deals!</em></p>

<h2>All Stores</h2>

{% for store in all_stores %}
<div class="store">
    <a href="/store/{{ store.id }}">{{ store.title }}</a> - 
    {{ store.items|length }} items
    <p><strong>Address:</strong> {{ store.address }}</p>
</div>
{% endfor %}

{% endblock %}

grocery_app/templates/item_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Item - {{ item.name }}</h1>

<form method="POST" action="/add_to_shopping_list/{{ item.id }}">
    <button type="submit">Add to Shopping List</button>
</form>

<p><img src="{{ item.photo_url }}" width="250px" height="250px"></p>

<p><strong>Price:</strong> {{ item.price }}</p>

<p><strong>Category:</strong> {{ item.category }}</p>

<p><strong>Store:</strong> {{ item.store.title }}</p>


<h2>Edit Item</h2>

<form method="POST">
    {{ form.hidden_tag() }}
    <fieldset>
        <legend>Please enter your information:</legend>



        <!-- TODO: Remove the next paragraph and use the `form` object passed in 
            from the route to render a form. -->
        {{ form.name.label }}
        {{ form.name }}
        <ul>
        {% for error in form.name.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.price.label }}
        {{ form.price }}
        <ul>
        {% for error in form.price.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.category.label }}
        {{ form.category }}
        <br>
        <br>
        {{ form.photo_url.label }}
        {{ form.photo_url }}
        <ul>
        {% for error in form.photo_url.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.store.label }}
        {{ form.store }}
        <br>
        <br>
        {{ form.submit }}
    </fieldset>
</form>

<p>Item created by: {{ item.created_by.username }}</p>

{% endblock %}

grocery_app/templates/login.html
{% extends 'base.html' %}
{% block content %}

<h1>Log In</h1>

<form action="/login" method="POST">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter your credentials</legend>

        {{ form.username.label }}
        {{ form.username }}
        <ul>
        {% for error in form.username.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.password.label }}
        {{ form.password }}
        <ul>
        {% for error in form.password.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

grocery_app/templates/new_item.html
{% extends 'base.html' %}
{% block content %}

<h1>New Item</h1>

<form method="POST">
    {{ form.hidden_tag() }}
    <fieldset>
        <legend>Please enter your information:</legend>



        <!-- TODO: Remove the next paragraph and use the `form` object passed in 
            from the route to render a form. -->
        {{ form.name.label }}
        {{ form.name }}
        <ul>
        {% for error in form.name.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.price.label }}
        {{ form.price }}
        <ul>
        {% for error in form.price.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.category.label }}
        {{ form.category }}
        <br>
        <br>
        {{ form.photo_url.label }}
        {{ form.photo_url }}
        <ul>
        {% for error in form.photo_url.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.store.label }}
        {{ form.store }}
        <br>
        <br>
        {{ form.submit }}
    </fieldset>
</form>


{% endblock %}

grocery_app/templates/new_store.html
{% extends 'base.html' %}
{% block content %}

<h1>New Store</h1>

<form method="POST" action="{{ url_for('main.new_store')}}">
    {{ form.hidden_tag() }}
    <fieldset>
        <legend>Please enter your information:</legend>



        <!-- TODO: Remove the next paragraph and use the `form` object passed in 
            from the route to render a form. -->
        {{ form.title.label }}
        {{ form.title }}
        <ul>
        {% for error in form.title.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.address.label }}
        {{ form.address }}
        {% for error in form.address.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.submit }}
    </fieldset>
</form>


{% endblock %}

grocery_app/templates/shopping_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Shopping List</h1>

{% for item in shopping_list %}
<div class="item-details">
    <a href="/item/{{ item.id }}"><img src="{{ item.photo_url }}" alt="{{ item.name }}" width="200px">
        <p><strong>{{ item.name }}</strong></p>
    </a>
    <p>Price: ${{ "%.2f"|format(item.price) }}</p>
    <form method="POST" action="/delete_from_shopping_list/{{ item.id }}">
        <input type="submit" value="Remove item">
    </form>
</div>
{% endfor %}

{% endblock %}

grocery_app/templates/signup.html
{% extends 'base.html' %}
{% block content %}

<h1>Sign Up</h1>

<form action="/signup" method="POST">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter your credentials</legend>

        {{ form.username.label }}
        {{ form.username }}
        <ul>
        {% for error in form.username.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.password.label }}
        {{ form.password }}
        <ul>
        {% for error in form.password.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

grocery_app/templates/store_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Store - {{ store.title }}</h1>

<strong>Address:</strong> {{ store.address }}

<h2>Items</h2>

<div class="items">
    {% for item in store.items %}
    <div class="item-details">
        <a href="/item/{{ item.id }}"><img src="{{ item.photo_url }}" alt="{{ item.name }}" width="200px">
        <p><strong>{{ item.name }}</strong></p></a>
        <p><strong>Price: ${{ item.price }}</strong></p>
    </div>
    {% endfor %}
</div>


<h2>Edit Store</h2>

<form method="POST">
    {{ form.hidden_tag() }}
    <fieldset>
        <legend>Please enter your information:</legend>



        <!-- TODO: Remove the next paragraph and use the `form` object passed in 
            from the route to render a form. -->
        {{ form.title.label }}
        {{ form.title }}
        <ul>
        {% for error in form.title.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.address.label }}
        {{ form.address }}
        {% for error in form.address.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.submit }}
    </fieldset>
</form>

<p>Store created by: {{ store.created_by.username }}</p>

{% endblock %}